;; 全角変換 M-x japanese-zenkaku-region
;; 半角変換 M-x japanese-hankaku-region
;; feedgeneratordで使用するmy-rss.pyの整形
;; 参考 http://d.hatena.ne.jp/gongoZ/20091127/1259330800
  (defun my-rss-replace ()
    (interactive)
    (let* ((num-begin 0)
           (num-end 0)
           (rss-num 0)
           (post-word (read-string "前置詞: " "//"))
           (post-length (length post-word))
           (search-word (concat "^" post-word "\\([0-9]+\\)$")))
      (progn (goto-char 0)
             (while (re-search-forward search-word nil t)
               (setq num-begin (+ (match-beginning 0) post-length)
                     num-end (match-end 0))
               (narrow-to-region num-begin num-end)
               (setq rss-num (string-to-number (buffer-string)))
               (delete-region (point-min) (point-max))
               (insert (number-to-string (+ rss-num 1)))
               (widen)))))
  (fset 'my-increment-number 'my-rss-replace)
;; Calenderでh m後に作られるhtmlファイルを整形するための関数
  (defun my-calender2html ()
    (interactive)
    (progn (goto-char 0)
           (re-search-forward "<HTML>\n<HEAD>" nil t)
           (delete-region (match-beginning 0) (match-end 0))
           (goto-char 0)
           (while (re-search-forward "</?\\([[:upper:]]+\\)" nil t)
             (downcase-region (match-beginning 0) (match-end 0)))
           (goto-char 0)
           (while (re-search-forward "[[:blank:]]+[[:upper:]]+[1-6]?\\([[:blank:]]\\|\.\\)" nil t)
             (downcase-region (match-beginning 0) (match-end 0)))
           (goto-char 0)
           (perform-replace "name=\\([[:digit:]]+\\)" "id=\"\\1\"" nil t nil)
           (goto-char 0)
           (insert (concat "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
                           "<!DOCTYPE html>\n"
                           "<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"ja\">\n"
                           "<head>\n"
                           "<meta charset=\"utf-8\" />\n"
                           "<meta http-equiv=\"content-type\" content=\"text/html\" />\n"
                           "<meta name=\"robots\" content=\"noindex,nofollow\" />\n"
                           "<meta name=\"author\" content=\"Toru Iijima\" />\n"))
           (re-search-forward "<style[^>]+>")
           (goto-char (+ (match-end 0) 1))
           (insert "<!--\n")
           (re-search-forward "</style>" nil t)
           (goto-char (match-beginning 0))
           (insert "-->\n")
           ;;  (goto-char 0)
           (re-search-forward "cal\.css" nil t)
           (goto-char (match-beginning 0))
           (insert "../")))
;;選択範囲内の全角英数字を半角英数字に変換
  (defun hankaku-eisuu-region (start end)
    (interactive "r")
    (while (string-match
            "[−！？０-９Ａ-Ｚａ-ｚ（）？！＝]+"
;;          "[０-９Ａ-Ｚａ-ｚ]+"
            (buffer-substring start end))
      (save-excursion
        (japanese-hankaku-region
         (+ start (match-beginning 0))
         (+ start (match-end 0))))))
;; Diaryで入力したテキストを整形するための関数
  (defun my-replace-string ()
    (interactive)
    (let ((FORM "")
          (REPLACEMENT "")
          (loopno 0))
      (goto-char 0)
      (while (re-search-forward "\\([−！？０-９Ａ-Ｚａ-ｚ（）？！＝]+\\)" nil t)
        (japanese-hankaku-region (match-beginning 0) (match-end 0)))
      (while (< loopno (length my-replace-list))
        (progn
          (setq FORM (car (nth loopno my-replace-list)))
          (setq REPLACEMENT (nth 1 (nth loopno my-replace-list)))
          (goto-char 0)
          (perform-replace FORM REPLACEMENT nil nil nil))
        (setq loopno (1+ loopno)))
      (setq loopno 0)
      (while (< loopno (length my-replace-reg-list))
        (progn
          (setq FORM (car (nth loopno my-replace-reg-list)))
          (setq REPLACEMENT (nth 1 (nth loopno my-replace-reg-list)))
          (goto-char 0)
          (perform-replace FORM REPLACEMENT nil 1 nil))
        (setq loopno (1+ loopno)))))
  (setq my-replace-list
        `(("％" "%")
          ("、" "，")
          ("。" "．")
          ("−" "-"))
        my-replace-reg-list
        `(("\\([0-9]+\\)\\(・\\|．\\)\\([0-9]+\\)" "\\1.\\3")
          ("\\([0-9]+\\)[./]\\([0-9]+\\)[./]\\([0-9]+\\) \\([0-9]+\\):\\([0-9]+\\)\\(更新\\)*" "\\1年\\2月\\3日 \\4時\\5分")))
  (defun my-html-tag-set (beg end)
    (interactive "r")
    (let* ((temp)
           (first-char-flag 0)
           (attr-body)
           (common-list '("id" "class" "lang" "title"))
           (tag-name (read-string "タグを指定して下さい: "))
           (flag (assoc tag-name attr-alist))
           (attr-list (append common-list (cdr (assoc tag-name attr-alist)))))
      (if flag
          (progn ;;(setq attribute-list (my-list-set a-attribute-list))
            (while (> (length attr-list) 0)
              (setq temp (read-string (format "%s:%d " (car attr-list) (length attr-list)))
                    attr-body (concat attr-body
                                      (if (> (length temp) 0)
                                          (concat (if (> (length attr-body) 0) " " "")
                                                  (format "%s=\"%s\"" (car attr-list) temp)) ""))
                    attr-list (cdr attr-list)))
;;	  (message (format "[%s]" attr-body))
;;	  (goto-char (if (> beg end) beg end))
            (narrow-to-region (if (> beg end) end beg) (if (> beg end) beg end))
            (hankaku-eisuu-region (point-min) (point-max))
            (goto-char (point-min))
            (perform-replace "\\(　\\| \\|\t\\)+$" "" nil 1 nil)
            (goto-char (point-max))
            (if (> (length (assoc tag-name single-tag-alist)) 0)
                (insert (format "<%s%s%s />" tag-name (if (> (length attr-body) 0) " " "") attr-body))
              (progn (insert (format "</%s>" tag-name))
                     (goto-char (point-min))
;		   (goto-char (if (> beg end) end beg))
                     (while (or (string= (string (following-char)) "　")
                                (string= (string (following-char)) " ")
                                (string= (string (following-char)) "\t"))
                       (delete-char 1))
                     (insert (format "<%s%s%s>" tag-name (if (> (length attr-body) 0) " " "") attr-body))))
            (widen)) "")))
  (setq single-tag-alist
        '(("area")("base")("br")("col")("embed")("img")("hr")("input")("keygen")("link")("meta")("param")("source")("track"))
        attr-alist
        '(
          ("a" "href" "hreflang" "media" "rel" "target" "type")
          ("abbr")
          ("address")
          ("area" "alt" "coords" "href" "hreflang" "media" "rel" "shape" "target" "type")
          ("article")
          ("aside")
          ("audio" "autoplay" "controls" "loop" "preload" "src")
          ("b")
          ("base" "href" "target")
          ("bdi")
          ("bdo" "dir")
          ("blockquote" "cite")
          ("body")
          ("br");single tag
          ("button" "autofocus" "disabled" "form" "formaction" "formenctype" "formmethod" "formnovalidate" "formtarget" "name" "type" "value")
          ("canvas" "height" "width")
          ("caption")
          ("cite")
          ("code")
          ("col" "span")
          ("colgroup" "span")
          ("command" "checked" "disabled" "icon" "label" "radiogroup" "type")
          ("datalist")
          ("dd")
          ("del" "cite" "datetime:YYYY-MM-DDThh:mm:ssTZD")
          ("details" "open")
          ("dfn")
          ("div")
          ("dl")
          ("dt")
          ("em")
          ("embed" "height" "src" "type" "width")
          ("fieldset" "disabled" "form" "name")
          ("figcaption")
          ("figure")
          ("footer")
          ("form" "accept-charset" "action" "autocomplate" "enctype" "method" "name" "novalidate" "target")
          ("h1")
          ("h2")
          ("h3")
          ("h4")
          ("h5")
          ("h6")
          ("head")
          ("header")
          ("hgroup")
          ("hr");single tag
          ("html" "manifest" "xmlns")
          ("i")
          ("iframe" "height" "name" "sandbox" "seamless" "src" "srcdoc" "width")
          ("img" "src" "alt" "height" "ismap" "usemap" "width")
          ("input" "accept" "alt" "autocomplate" "autofocus" "checked" "disabled" "form" "formaction" "formenctype" "formmethod" "formnovalidate" "formtaget" "height" "list" "max" "maxlength" "min" "multiple" "name" "pattern" "placeholder" "readonly" "required" "size" "src" "step" "type" "value" "width")
          ("ins" "cite" "datetime=YYYY-MM-DDThh:mm:ssTZD")
          ("kbd")
          ("keygen" "autofocus" "challenge" "disabled" "form" "keytype" "name")
          ("legend")
          ("li" "value")
          ("link" "href" "hreflang" "media" "rel" "sizes" "type")
          ("map" "name")
          ("mark")
          ("menu" "label" "type")
          ("meta" "charset" "content" "http-equiv" "name")
          ("meter" "form" "high" "low" "max" "min" "optimum" "value")
          ("nav")
          ("noscript")
          ("object" "data" "form" "height" "name" "type" "usemap" "width")
          ("ol" "reversed" "start" "type")
          ("optgroup" "label" "disabled")
          ("option" "disabled" "label" "selected" "value")
          ("output" "for" "form" "name")
          ("p")
          ("param" "name" "value")
          ("pre")
          ("progress" "max" "value")
          ("q" "cite")
          ("rp")
          ("rt")
          ("ruby")
          ("s")
          ("samp")
          ("script" "async" "defer" "type" "charset" "src" "xml:space")
          ("section")
          ("select" "autofocus" "desabled" "form" "multiple" "name" "size")
          ("small")
          ("source" "media" "src" "type")
          ("span")
          ("strong")
          ("style" "type" "media" "scoped")
          ("sub")
          ("summary")
          ("sup")
          ("table" "border")
          ("tbody")
          ("td" "colspan" "headers" "rowspan")
          ("textarea" "autofocus" "cols" "disabled" "form" "maxlength" "name" "placeholder" "readonly" "required" "rows" "wrap")
          ("tfoot")
          ("th" "colspan" "headers" "rowspan" "scope")
          ("thead")
          ("time" "datetime" "pubdate")
          ("title")
          ("tr")
          ("track" "default" "kind" "label" "src" "srclang")
          ("ul")
          ("var")
          ("video" "autoplay" "controls" "height" "loop" "muted" "poster" "preload" "src" "width")
          ("wbr")
          )
        rel-list
        '("alternate" "author" "bookmark" "help" "license" "next" "nofollow" "noreferrer" "prefetch" "prev" "search" "tag")
        shape-list
        '("default" "rect" "circle" "poly")
        target-list
        '("_blank" "_parent" "_self" "_topframename")
        bdo-list
        `("ltr" "rtl")
        formtarget-list
        '("_blank" "_parent" "_self" "_topframename")
        command-type-list
        '("checkbox" "command" "radio")
        form-method-list
        '("get" "post")
        form-target-list
        '("_blank" "_self" "_parent" "_top")
        iframe-sandbox-list
        '("\"\"" "allow-forms" "allow-same-origin" "allow-scripts" "allow-top-navigation")
        input-autocomplate-list
        '("on" "off")
        input-type-list
        '("button" "checkbox" "color" "date" "datetime" "datetime-local" "email" "file" "hidden" "image" "manth" "number" "password" "radio" "range" "reset" "search" "submit" "tel" "text" "time" "url" "week")
        keygen-keytype-list
        '("rsa" "dsa" "ec")
        link-rel-list
        '("alternate" "archives" "autor" "bookmark" "external" "first" "help" "icon" "last" "licence" "next" "nofollow" "noreferrer" "pingback" "prefetch" "prev" "search" "sidebar" "stylesheet" "tag" "up")
        menu-type-list
        '("context" "toolbar" "list")
        meta-http-equive-list
        '("content-type" "default-style" "refresh")
        meta-name-list
        '("application-name" "autor" "description" "generatorkeywords")
        ol-type-list
        '("1" "A" "a" "I" "i")
        textarea-wrap-list
        '("hard" "soft")
        th-scope-list
        '("col" "colgroup" "row" "rowgroup")
        track-kind-list
        '("captions" "chapters" "descriptions" "metadata" "subtitles")
        video-preload-list
        '("auto" "metadata" "none")
        )
  (defun my-ruby-set (beg end)
    (interactive "r")
    (let ((starttag "<ruby>")
          (middletag "<rp>(</rp><rt>")
          (endtag "</rt><rp>)</rp></ruby>")
          (ruby (read-string "ふりがな: ")))
      (save-excursion
        (progn (if (= (length ruby) 0)
                   (progn (goto-char end)
                          (if (string= (string (following-char)) "(")
                              (progn (re-search-forward "\([^)]+\)");(mark-sexp);
                                     (setq ruby (substring
                                                 (buffer-substring (match-beginning 0) (match-end 0))
                                                 1 (- (match-end 0) (match-beginning 0) 1)))
                                     (kill-region (match-beginning 0) (match-end 0))))))
               (goto-char end)
               (insert middletag)
               (if (= (length ruby) 0)
                   (setq ruby (read-string "ルビを指定してください: ")))
               (insert ruby)
               (insert endtag)
               (goto-char beg)
               (insert starttag)))
      (goto-char (+ end (length starttag) (length middletag) (length ruby) (length endtag)))))
  (defun my-html-lang-set (beg end)
    (interactive "r")
    (japanese-hankaku-region (if (> beg end) end beg)
                             (if (> beg end) beg end))
    (progn (goto-char (if (> beg end) beg end))
           (insert "</span>")
           (goto-char (if (> beg end) end beg))
           (insert "<span lang=\"en-us\">")
           (goto-char (+ (if (> beg end) beg end)
                         (length "</span>")
                         (length "<span lang=\"en-us\">")))))
  (defun my-html-abbr-set (beg end)
    (interactive "r")
    (japanese-hankaku-region (if (> beg end) end beg)
                             (if (> beg end) beg end))
    (let* ((abbr-key (buffer-substring-no-properties beg end))
           (abbr-value (nth 1 (assoc abbr-key my-html-abbr-alist)))
           (abbr-value-jp (nth 2 (assoc abbr-key my-html-abbr-alist)))
           (abbr-beg-tag (format "<abbr lang=\"en-us\" title=\"%s" abbr-value))
           (abbr-end-tag "</abbr>"))
      (if (> (length abbr-value) 0)
          (progn (goto-char (if (> beg end) beg end))
                 (insert abbr-end-tag)
                 (goto-char (if (> beg end) end beg))
                 (if (> (length abbr-value-jp) 0)
                     (if (y-or-n-p (format "\"%s\"もtitleに設定しますか？" abbr-value-jp))
                         (setq abbr-beg-tag (format "%s,%s" abbr-beg-tag abbr-value-jp)) "") "")
                 (insert (format "%s\">" abbr-beg-tag))
                 (goto-char (+ (if (> beg end) beg end)
                               (length (format "%s\">%s" abbr-beg-tag abbr-end-tag)))))
        (message (format "\"%s\"はないなぁ :-<" abbr-key)))))
  (setq my-html-abbr-alist
        '(
          ("A2AD" "Anti Access Area Denial" "接近阻止・領域拒否")
          ("A2/AD" "Anti Access Area Denial" "接近阻止・領域拒否")
          ("AAAS" "American Association for the Advancement of Science" "アメリカ科学振興協会")
          ("ABM" "antiballistic missile" "弾道弾迎撃ミサイル")
          ("ABS" "anti-lock breke system")
          ("ACSA" "Acquisition and Cross-Servicing Agreement" "物品役務相互提供協定")
          ("ADB" "Asian Development Bank" "アジア開発銀行")
          ("ADIZ" "Air Defense Identification Zone" "防空識別圏")
          ("AFP" "Agence France-Presse")
          ("AIIB" "Asian Infrastructure Investment Bank" "アジアインフラ投資銀行")
          ("AIS" "automatic identification system" "自動船舶識別装置")
          ("AP" "Associated Press")
          ("APEC" "Asia-Pacific Economic Cooperration" "アジア太平洋経済協力会議")
          ("ASAT" "anti-satelite weapon" "衛星攻撃兵器")
          ("ASBM" "Anti-ship Ballistic Missile" "対艦弾道ミサイル")
          ("ASEAN" "Association of SouthEast Asian Nations" "東南アジア諸国連合")
          ("ASEM" "ASia-Europe Meeting" "アジア欧州会合")
          ("ATM" "automatic teller machine")
          ("AWACS" "Airborne Warning And Control System" "空中警戒管制機")
          ("BBC" "British Broadcasting Corporation" "英国放送協会")
          ("BBS" "bulletin board system")
          ("bcc" "blind carbon copy")
          ("BD" "Blu-ray Disc")
          ("BMD" "Ballistic Missile Defense" "弾道ミサイル防衛")
          ("BPO" "Broadcasting Ethics and Program Improvement Organization" "放送倫理・番組向上機構")
          ("BSE" "bovine spongiform encephalopathy" "牛海綿状脳症")
          ("cc" "carbon copy")
          ("CD" "Compact Disc")
          ("CDC" "Center for Disease Control and Prevention" "米国疾病予防管理センター")
          ("CEO" "chief executive officer" "最高経営責任者")
          ("CG" "Computer Graphics")
          ("CIA" "Central Intelligence Agency" "米国中央情報局")
          ("CIO" "chief infomation officer" "最高情報責任者")
          ("CIS" "Commonwealth of Independent States" "独立国家共同体")
          ("CPU" "Central Processing Unit" "中央演算処理装置")
          ("CSIS" "Center for Strategic and International Studies" "戦略国際問題研究所")
          ("CSS" "Cascading Style Sheets")
          ("CTBT" "Comprehensive Nuclear-Test-Ban Treaty" "包括的核実験禁止条約")
          ("CTBTO" "Comprehensive Nuclear-Test-Ban Treaty Organization" "包括的核実験禁止条約機関")
          ("CTF" "Combined Task Force" "連合任務部隊")
          ("CTF151" "Combined Task Force 151" "第151連合任務部隊")
          ("CWC" "Chemical Weapons Convention" "化学兵器禁止条約")
          ("DDoS" "distributed denial of services attack" "分散型サービス拒否攻撃")
          ("DHA" "docosahexaenoic acid" "ドコサヘキサエン酸")
          ("DIA" "Defense Intelligence Agency")
          ("DMAT" "Disaster Medical Asistance Team" "災害派遣医療チーム")
          ("DMZ" "demilitarized zone" "非武装地帯")
          ("DNA" "DeoxyriboNucleic Acid" "デオキシリボ核酸")
          ("DVD" "Digital Versatile Disc")
          ("EAEC" "East Asia Economic Caucus" "東アジア経済会議")
          ("EC" "European Community" "欧州共同体")
          ("ECAFE" "Economic Commission for Asia and the Far East" "アジア極東経済委員会")
          ("ECOSOC" "Economic and Social Council" "経済社会理事会")
          ("EEZ" "Exclusive Economic Zone" "排他的経済水域")
          ("EPA" "economic partnership agreement")
          ("ESA" "European Space Agency" "欧州宇宙機関")
          ("ESC" "Economic and Social Council" "経済社会理事会")
          ("ESD" "education for sustainable development" "持続可能な開発のための教育")
          ("EU" "European Union" "欧州連合")
          ("FAO" "Food and Agriculture Organization of the United Nations" "国連食糧農業機関")
          ("FATF" "Financial Action Task Force on Money Laundering" "金融活動作業部会")
          ("FBI" "Federal Bureau of Investigation" "連邦捜査局")
          ("FDA" "Food and Drug Administration" "食品医薬品局")
          ("FMS" "foreign military sales" "対外有償軍事援助")
          ("FRB" "Federal Reserve Board" "米連邦準備制度理事会")
          ("FRP" "Fiber Reinforced Plastics" "繊維強化プラスチック")
          ("FTA" "free trade agreement" "自由貿易協定")
          ("FTAAP" "Free Trade Area of the Asia Pacific" "アジア太平洋自由貿易圏")
          ("G7" "The Conference of Ministers and Governors of the Group of Seven" "主要7ヶ国財務相・中央銀行総裁会議")
          ("GBI" "graund based interceptor")
          ("GDP" "Gross Domestic Product" "国内総生産")
          ("GHQ" "General Headquarters" "連合国軍最高司令官総司令部")
          ("GNI" "Gross National Income" "国民総所得")
          ("GNP" "Gross National Product" "国民総生産")
          ("GPS" "Global Positioning System" "汎地球測位システム")
          ("GRU" "Glavnoye Razvedyvatelnoye Upravleniye" "ロシア連邦軍参謀本部情報総局")
          ("GSOMIA" "General Security of Military Information Agreement" "軍事情報包括保護協定")
          ("HIV" "Human Immunodeficiency Virus")
          ("HTML" "Hyper Text Markup Language")
          ("HTTP" "hypertext transfer protocol")
          ("IAEA" "International Atomic Energy Agency" "国際原子力機関")
          ("IARC" "International Agency for Research on Cancer" "国際癌研究機関")
          ("IBRD" "International Bank for Reconstruction and Development" "国際復興開発銀行")
          ("ICAO" "International Civil Aviation Organization" "国際民間航空機関")
          ("ICBM" "InterContinental Ballistic Missile" "大陸間弾道ミサイル")
          ("ICC" "International Criminal Court" "国際刑事裁判所")
          ("ICJ" "International Court of Justice" "国際司法裁判所")
          ("ICPO" "International Criminal Police Organization" "国際刑事警察機構")
          ("ICSID" "International Centre for Settlement of Investment Disputes" "国際投資紛争解決センター")
          ("IDA" "International Development Association" "国際開発協会")
          ("IFAD" "Internatilnal Fund for Agricultural Development" "国際農業開発基金")
          ("IFC" "International Finance Corporation" "国際金融公社")
          ("IHO" "International Hydrographic Organization" "国際水路機関")
          ("ILO" "International Labor Organization" "国際労働機関")
          ("IMF" "International Monetary Fund" "国際通貨基金")
          ("IMO" "International Maritime Organization" "国際海事機関")
          ("INES" "International Nuclear and Radiological Event Scale" "国際原子力事象評価尺度")
          ("IOC" "International Olympic Committee" "国際オリンピック委員会")
          ("IP" "Internet Protocol")
          ("IPCC" "Intergovernmental Panel on Climete Change" "気候変動に関する政府間パネル")
          ("iPS" "induces Pluripotent Stem cell")
          ("ISAF" "International Security Assistance Force" "国際治安支援部隊")
          ("ISIL" "Islamic State in Iraq and the Levant" "イラクとレバントのイスラーム国")
          ("ISR" "intelligence, surveillance and reconnaissance" "情報・監視・偵察")
          ("ISS" "International Space Station" "国際宇宙ステーション")
          ("IT" "Infomation Technology" "情報技術")
          ("ITLOS" "International Tribunal for the Law of the Sea" "国際海洋法裁判所")
          ("ITU" "International Telecommunication Union" "国際電気通信連合")
          ("IWC" "International Whaling Commission" "国際捕鯨委員会")
          ("JA" "Japan Agricultural Cooperatives")
          ("JAEA" "Japan Atomic Energy Agency" "日本原子力研究開発機構")
          ("JAS" "Japanese Agricultural Standard" "日本農林規格")
          ("JASDAQ" "Japan Securities Dealers Association Quotation System")
          ("JASDF" "Japan Air Self-Defense Force" "航空自衛隊")
          ("JASRAC" "Japanese Society for Rights of Authors, Composers and Publishers" "日本音楽著作権協会")
          ("LAV" "Light Armored Vehicle")
          ("JAXA" "Japan Aerospace Exploration Agency" "宇宙航空研究開発機構")
          ("JBIC" "Japan Bank for International Cooperation" "国際協力銀行")
          ("JICA" "Japan International Cooperation Agency" "国際協力機構")
          ("JIS" "Japanese Industrial Standards" "日本工業規格")
          ("JOGMEC" "Japan Oil, Gas and Metals National Corporation" "石油天然ガス・金属鉱物資源機構")
          ("JR" "Japan Railways")
          ("JRA" "Japan Racing Association" "日本中央競馬会")
          ("JRCS" "Japanese Red Cross Society" "日本赤十字社")
          ("J-PARC" "Japan Proton Accelerator Reserce Complex")
          ("KGB" "Komitet Gosudarstvennoi Bezopasnosti")
          ("LAN" "Local Area Network")
          ("LCC" "Low-Cost Carrier" "格安航空会社")
          ("LED" "Light Emitting Diode" "発光ダイオード")
          ("LHC" "Large Hadron Collider" "大型ハドロン衝突型加速器")
          ("LN" "League of Nations" "国際連盟")
          ("LPG" "Liquefied Petroleum Gas" "液化石油ガス")
          ("LNG" "liquefied natural gas" "液化天然ガス")
          ("MD" "missile defense" "ミサイル防衛")
          ("MERS" "Middle East Respiratory Syndrome" "中東呼吸器症候群")
          ("MI6" "Military Intelligence 6")
          ("MIGA" "Multilateral Investment Guarantee Agency" "多数国間投資保証機関")
          ("MIRV" "Multiple Independently-targetable Reentry Vehicle")
          ("MP" "Military Police" "米国陸軍憲兵隊")
          ("MRI" "Magnetic Resonance Imaging" "磁気共鳴映像法")
          ("NASA" "National Aeronautics and Space Administration" "アメリカ航空宇宙局")
          ("NATO" "North Atlantic Treaty Organization" "北大西洋条約機構")
          ("NEDO" "New Energy and Industrial Technology Develpment Organization" "新エネルギー・産業技術総合開発機構")
          ("NGO" "NonGovernmental Organization" "非政府組織")
          ("NHK" "Nippon Hoso Kyokai" "日本放送協会")
          ("NHTSA" " National Highway Traffic Safety Administration" "国家道路交通安全局")
          ("NICT" "Nationa Instirute of Information and Communications Technology" "情報通信研究機構")
          ("NISC" "National Infomation Security Center" "内閣官房情報セキュリティセンター")
          ("NLL" "Northern Limit Line" "北方境界線")
          ("NOAA" "National Oceanic and Atmospheric Administration" "アメリカ海洋大気庁")
          ("NORAD" "North American Aerospace Defense Command" "北アメリカ航空宇宙防衛司令部")
          ("NPO" "Non-Profit Organization" "民間非営利団体")
          ("NPT" "Non-Proliferation Treaty" "核不拡散条約")
          ("NRC" "Nuclear Regulatory Commission" "原子力規制委員会")
          ("NSA" "National Security Agency" "国家安全保障局")
          ("NSC" "National Security Council" "国家安全保障会議")
          ("NTT" "Nippon Telegraph and Telephone Company" "日本電信電話会社")
          ("OCHA" "Office for the Coordination of Humanitarian Affairs" "国連人道問題調整部")
          ("ODA" "Offcial Development Assistance" "政府開発援助")
          ("OECD" "Organization for Economic Cooperation and Development" "経済協力開発機構")
          ("OIE" "Office International des Epizooties" "国際獣疫事務局")
          ("OPCW" "Organisation for the Prohibition of Chemical Weapons" "化学兵器禁止機関")
          ("OS" "Operating System")
          ("PAC3" "Patriot advanced capability 3")
          ("PC" "Personal Computer")
          ("PIF" "Pacific Islands Forum" "太平洋諸島フォーラム")
          ("PKF" "PeaceKeeping Force" "国連平和維持軍")
          ("PKO" "PeaceKeeping Operations" "国連平和維持活動")
          ("PSI" "Proliferation Security Initiative" "大量破壊兵器拡散阻止構想")
          ("PTA" "Parent-Teacher Association" "父母と教師の会")
          ("ReCAAP" "Regional Cooperation Agreement on Combating Piracy and Armed Robbery against Ships in Asia" "アジア海賊対策地域協力協定")
          ("RECAAP" "Regional Cooperation Agreement on Combating Piracy and Armed Robbery against Ships in Asia" "アジア海賊対策地域協力協定")
          ("ROE" "Rules of Engagement" "部隊行動基準")
          ("ROV" "remotely-operated vehicle" "水中無人探査機")
          ("RSF" "Reporters Sans Fronti&#233;res" "国境なき記者団")
          ("SAM" "surface-to-air missile" "地対空ミサイル")
          ("SARS" "Severe Acute Respiratory Syndrome" "重症急性呼吸器症候群")
          ("SAT" "scholastic assessment test" "大学進学適性試験")
          ("SEC" "Securities and Exchange Commission" "米国証券取引委員会")
          ("SF" "Science Fiction" "空想科学小説")
          ("SIPRI" "Stockholm International Peace Research Institute" "ストックホルム国際平和研究所")
          ("SLBM" "Submarine-Launched Ballistic Missile" "潜水艦発射弾道ミサイル")
          ("SPC" "Special Purpose Company")
          ("SNS" "Social Networking Service")
          ("SOFA" "Japan Status of Forces Agreement")
          ("SOSUS" "sound surveillance system")
          ("SSBN" "Ballistic Missile Submarine Nuclear-Powered" "弾道ミサイル搭載原子潜水艦")
          ("SSM" "surface-to-surface missile" "地対地ミサイル，地対艦ミサイル")
          ("TC" "Trusteeship Council")
          ("TEL" "transporter-elector-launcher")
          ("THAAD" "terminal high altitude area defense" "最終段階高高度地域防衛")
          ("TICAD" "Tokyo Internation Conference on Afrecan Development" "アフリカ開発会議")
          ("TNT" "trinitrotoluene" "トリニトロトルエン")
          ("TOEIC" "Test of English International Communication" "国際コミュニケーション英語能力テスト")
          ("TPP" "Trans-Pacific Strategic Economic Partnership Agreement" "環太平洋戦略的経済連携協定")
          ("UAE" "United Arab Emirates" "アラブ首長国連邦")
          ("UFO" "Unidentified Flying Object" "未確認飛行物体")
          ("UN" "United Nations" "国際連合")
          ("UNC" "Charter of the United Nations" "国連憲章")
          ("UNDOF" "United Nations Disengagement Observer Force" "国連兵力引き離し監視軍")
          ("UNESCO" "United Nations Educational, Scientific and Cultural Organization" "国連教育科学文化機関")
          ("UNGA" "United Nations General Assembly" "国連総会")
          ("UNHCR" "Office of the United Nations High Commissioner for Refugees" "国連高等難民弁務官事務所")
          ("UNIDO" "United Nations Industrial Development Organization" "国連工業開発機関")
          ("UNSCEAR" "United Nations Scientific Committee on the Effects of Atomic Radiation")
          ("UNTC" "United Nations Trusteeship Council")
          ("UNODC" "United Nations Office on Drugs and Crime" "国連薬物犯罪事務所")
          ("UPU" "Universal Postal Union" "万国郵便連合")
          ("URL" "Uniform Resource Locator")
          ("USGS" "United States Geological Survey" "アメリカ地質調査所")
          ("VANK" "Voluntary Agancy Network Korean")
          ("VIP" "very important person")
          ("WBC" "World Baseball Classic")
          ("WGIP" "War Guilt Information Program")
          ("WHO" "World Health Organization" "世界保健機関")
          ("Wi-Fi" "Wireless Fidelity")
          ("WiFi" "Wireless Fidelity")
          ("WIPO" "World Intellectual Property Organization" "世界知的所有権機関")
          ("WMO" "World Meteorological Organization" "世界気象機関")
          ("WTO" "World Trade Organization" "世界貿易機関")
          ))
;(fset 'InputTeX
;      (lambda (&optional arg)
;        "Keyboard macro."
;        (interactive "p")
;        (kmacro-exec-ring-item
;         (quote ([32 119 47 32 50 32 119 45 49 50 32 119 46 125 113 32 102 114 111 114 103 32 116 111 100 111 return
;                     32 102 114 111 114 103 32 115 112 97 99 101 return
;                     32 102 114 98 117 110 110 121 97 32 111 114 103 return] 0 "%d")) arg)))
(fset 'InputTeX
      (lambda (&optional arg)
        "Keyboard macro."
        (interactive "p")
        (kmacro-exec-ring-item
         (quote ([32 119 47 32 50 32 119 45 49 50 32 119 46 125 113] 0 "%d")) arg)))
(provide 'my-setting)
